MAIN_PAGE_URL = "https://artnow.ru/"
VYSHITYE_KARTINY_URL = "https://artnow.ru/vyshitye-kartiny-kupit.html"
BATIK_KARTINY_URL = "https://artnow.ru/batik-kartiny-kupit.html"
JUVELIRNYE_IZDELIJA_URL = "https://artnow.ru/juvelirnye-izdelija-ruchnoj-raboty.html"
SEARCH_PAGE_URL = "https://artnow.ru/ru/searchpage.html"
FAVORITES_URL = "https://artnow.ru/ru/favorites.html"
BASKET_URL = "https://artnow.ru/index.html"
